services:
  mssql-db:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: glucopilot-mssql-db
    restart: always
    environment:
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - glucopilot-sql-data:/var/opt/mssql

  glucopilot-api:
    container_name: glucopilot-api
    build:
      context: ../src
      dockerfile: ./GlucoPilot.Api/Dockerfile
    depends_on:
      - mssql-db
    environment:
      Data__ConnectionString: "Server=mssql-db;Database=GlucoPilot;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True"
      Identity__TokenExpirationInMinutes: "60"
      Identity__TokenSigningKey: ${IDENTITY_TOKEN_SIGNING_KEY}
      Mail__SmtpHost: ${SMTP_HOST}
      Mail__Port: ${SMTP_PORT}
      Mail__SmtpUser: ${SMTP_USER}
      Mail__SmtpPassword: ${SMTP_PASSWORD}
      Mail__DisplayName: ${SMTP_DISPLAY_NAME}
      Mail__From: ${SMTP_FROM}
    ports:
      - "8080:8080"
      - "8081:8081"

volumes:
  glucopilot-sql-data:
    external: false