//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlucoPilot.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("GlucoPilot.Resources.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        public static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        public static string PasswordMinLength {
            get {
                return ResourceManager.GetString("PasswordMinLength", resourceCulture);
            }
        }
        
        public static string ConfirmPasswordRequired {
            get {
                return ResourceManager.GetString("ConfirmPasswordRequired", resourceCulture);
            }
        }
        
        public static string ConfirmPasswordNotMatch {
            get {
                return ResourceManager.GetString("ConfirmPasswordNotMatch", resourceCulture);
            }
        }
        
        public static string TermsNotAccepted {
            get {
                return ResourceManager.GetString("TermsNotAccepted", resourceCulture);
            }
        }
        
        public static string TokenRequired {
            get {
                return ResourceManager.GetString("TokenRequired", resourceCulture);
            }
        }
        
        public static string InjectionIdRequiredWhenAllNull {
            get {
                return ResourceManager.GetString("InjectionIdRequiredWhenAllNull", resourceCulture);
            }
        }
        
        public static string ReadingIdRequiredWhenAllNull {
            get {
                return ResourceManager.GetString("ReadingIdRequiredWhenAllNull", resourceCulture);
            }
        }
        
        public static string MealdInjectionIdMustBeProvided {
            get {
                return ResourceManager.GetString("MealdInjectionIdMustBeProvided", resourceCulture);
            }
        }
        
        public static string CannotBeFutureDate {
            get {
                return ResourceManager.GetString("CannotBeFutureDate", resourceCulture);
            }
        }
        
        public static string LevelGreaterThanZero {
            get {
                return ResourceManager.GetString("LevelGreaterThanZero", resourceCulture);
            }
        }
        
        public static string ToBeforeFrom {
            get {
                return ResourceManager.GetString("ToBeforeFrom", resourceCulture);
            }
        }
        
        public static string IntervalInvalid {
            get {
                return ResourceManager.GetString("IntervalInvalid", resourceCulture);
            }
        }
        
        public static string MealIdRequiredWhenAllNull {
            get {
                return ResourceManager.GetString("MealIdRequiredWhenAllNull", resourceCulture);
            }
        }
        
        public static string IngredientIdInvalid {
            get {
                return ResourceManager.GetString("IngredientIdInvalid", resourceCulture);
            }
        }
        
        public static string QuantityGreaterThanZero {
            get {
                return ResourceManager.GetString("QuantityGreaterThanZero", resourceCulture);
            }
        }
        
        public static string MealIdInvalid {
            get {
                return ResourceManager.GetString("MealIdInvalid", resourceCulture);
            }
        }
        
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        public static string PatientIdRequired {
            get {
                return ResourceManager.GetString("PatientIdRequired", resourceCulture);
            }
        }
        
        public static string InsulinTypeInvalid {
            get {
                return ResourceManager.GetString("InsulinTypeInvalid", resourceCulture);
            }
        }
        
        public static string DurationGreaterThanZero {
            get {
                return ResourceManager.GetString("DurationGreaterThanZero", resourceCulture);
            }
        }
        
        public static string ScaleGreaterThanZero {
            get {
                return ResourceManager.GetString("ScaleGreaterThanZero", resourceCulture);
            }
        }
        
        public static string PeaktimeGreaterThanZero {
            get {
                return ResourceManager.GetString("PeaktimeGreaterThanZero", resourceCulture);
            }
        }
        
        public static string InsulinIdInvalid {
            get {
                return ResourceManager.GetString("InsulinIdInvalid", resourceCulture);
            }
        }
        
        public static string UnitsGreaterThanZero {
            get {
                return ResourceManager.GetString("UnitsGreaterThanZero", resourceCulture);
            }
        }
        
        public static string CreatedDateRequired {
            get {
                return ResourceManager.GetString("CreatedDateRequired", resourceCulture);
            }
        }
        
        public static string IngredientsNotEmpty {
            get {
                return ResourceManager.GetString("IngredientsNotEmpty", resourceCulture);
            }
        }
        
        public static string CarbsGreaterThanOrEqualToZero {
            get {
                return ResourceManager.GetString("CarbsGreaterThanOrEqualToZero", resourceCulture);
            }
        }
        
        public static string ProteinGreaterThanOrEqualToZero {
            get {
                return ResourceManager.GetString("ProteinGreaterThanOrEqualToZero", resourceCulture);
            }
        }
        
        public static string FatGreaterThanOrEqualToZero {
            get {
                return ResourceManager.GetString("FatGreaterThanOrEqualToZero", resourceCulture);
            }
        }
        
        public static string CaloriesGreaterThanOrEqualToZero {
            get {
                return ResourceManager.GetString("CaloriesGreaterThanOrEqualToZero", resourceCulture);
            }
        }
        
        public static string SearchLengthInvalid {
            get {
                return ResourceManager.GetString("SearchLengthInvalid", resourceCulture);
            }
        }
    }
}
