//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlucoPilot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GlucoPilot.Resources.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CALORIES_GREATER_THAN_OR_EQUAL_TO_ZERO.
        /// </summary>
        public static string CaloriesGreaterThanOrEqualToZero {
            get {
                return ResourceManager.GetString("CaloriesGreaterThanOrEqualToZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANNOT_BE_FUTURE_DATE.
        /// </summary>
        public static string CannotBeFutureDate {
            get {
                return ResourceManager.GetString("CannotBeFutureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CARBS_GREATER_THAN_OR_EQUAL_TO_ZERO.
        /// </summary>
        public static string CarbsGreaterThanOrEqualToZero {
            get {
                return ResourceManager.GetString("CarbsGreaterThanOrEqualToZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIRM_PASSWORD_NOT_MATCH.
        /// </summary>
        public static string ConfirmPasswordNotMatch {
            get {
                return ResourceManager.GetString("ConfirmPasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIRM_PASSWORD_REQUIRED.
        /// </summary>
        public static string ConfirmPasswordRequired {
            get {
                return ResourceManager.GetString("ConfirmPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATED_DATE_REQUIRED.
        /// </summary>
        public static string CreatedDateRequired {
            get {
                return ResourceManager.GetString("CreatedDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DURATION_GREATER_THAN_ZERO.
        /// </summary>
        public static string DurationGreaterThanZero {
            get {
                return ResourceManager.GetString("DurationGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMIAL_INVALID.
        /// </summary>
        public static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMAIL_REQUIRED.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAT_GREATER_THAN_OR_EQUAL_TO_ZERO.
        /// </summary>
        public static string FatGreaterThanOrEqualToZero {
            get {
                return ResourceManager.GetString("FatGreaterThanOrEqualToZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INGREDIENT_ID_INVALID.
        /// </summary>
        public static string IngredientIdInvalid {
            get {
                return ResourceManager.GetString("IngredientIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INGREDIENTS_NOT_EMPTY.
        /// </summary>
        public static string IngredientsNotEmpty {
            get {
                return ResourceManager.GetString("IngredientsNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INJECTION_ID_REQUIRED_WHEN_ALL_NULL.
        /// </summary>
        public static string InjectionIdRequiredWhenAllNull {
            get {
                return ResourceManager.GetString("InjectionIdRequiredWhenAllNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSULIN_ID_INVALID.
        /// </summary>
        public static string InsulinIdInvalid {
            get {
                return ResourceManager.GetString("InsulinIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSULIN_NOT_FOUND.
        /// </summary>
        public static string InsulinNotFound {
            get {
                return ResourceManager.GetString("InsulinNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSULIN_TYPE_INVALID.
        /// </summary>
        public static string InsulinTypeInvalid {
            get {
                return ResourceManager.GetString("InsulinTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INTERVAL_INVALID.
        /// </summary>
        public static string IntervalInvalid {
            get {
                return ResourceManager.GetString("IntervalInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEVEL_GREATER_THAN_ZERO.
        /// </summary>
        public static string LevelGreaterThanZero {
            get {
                return ResourceManager.GetString("LevelGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEAL_ID_INJECTION_ID_MUST_BE_PROVIDED.
        /// </summary>
        public static string MealdInjectionIdMustBeProvided {
            get {
                return ResourceManager.GetString("MealdInjectionIdMustBeProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEAL_ID_INVALID.
        /// </summary>
        public static string MealIdInvalid {
            get {
                return ResourceManager.GetString("MealIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEAL_ID_REQUIRED_WHEN_ALL_NULL.
        /// </summary>
        public static string MealIdRequiredWhenAllNull {
            get {
                return ResourceManager.GetString("MealIdRequiredWhenAllNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAME_REQUIRED.
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASSWORD_MIN_LENGTH.
        /// </summary>
        public static string PasswordMinLength {
            get {
                return ResourceManager.GetString("PasswordMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASSWORD_REQUIRED.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PATIENT_ID_REQUIRED.
        /// </summary>
        public static string PatientIdRequired {
            get {
                return ResourceManager.GetString("PatientIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PEAKTIME_GREATER_THAN_ZERO.
        /// </summary>
        public static string PeaktimeGreaterThanZero {
            get {
                return ResourceManager.GetString("PeaktimeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PEN_COLOUR_INVALID.
        /// </summary>
        public static string PenColourInvalid {
            get {
                return ResourceManager.GetString("PenColourInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PEN_MODEL_INVALID.
        /// </summary>
        public static string PenModelInvalid {
            get {
                return ResourceManager.GetString("PenModelInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PEN_SERIAL_INVALID.
        /// </summary>
        public static string PenSerialInvalid {
            get {
                return ResourceManager.GetString("PenSerialInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PEN_SERIAL_REQUIRED.
        /// </summary>
        public static string PenSerialRequired {
            get {
                return ResourceManager.GetString("PenSerialRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PEN_SERIAL_TOO_LONG.
        /// </summary>
        public static string PenSerialTooLong {
            get {
                return ResourceManager.GetString("PenSerialTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROTEIN_GREATER_THAN_OR_EQUAL_TO_ZERO.
        /// </summary>
        public static string ProteinGreaterThanOrEqualToZero {
            get {
                return ResourceManager.GetString("ProteinGreaterThanOrEqualToZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUANTITY_GREATER_THAN_ZERO.
        /// </summary>
        public static string QuantityGreaterThanZero {
            get {
                return ResourceManager.GetString("QuantityGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RANGE_GREATER_THAN_ZERO.
        /// </summary>
        public static string RangeGreaterThanZero {
            get {
                return ResourceManager.GetString("RangeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to READING_ID_REQUIRED_WHEN_ALL_NULL.
        /// </summary>
        public static string ReadingIdRequiredWhenAllNull {
            get {
                return ResourceManager.GetString("ReadingIdRequiredWhenAllNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCALE_GREATER_THAN_ZERO.
        /// </summary>
        public static string ScaleGreaterThanZero {
            get {
                return ResourceManager.GetString("ScaleGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEARCH_LENGTH_INVALID.
        /// </summary>
        public static string SearchLengthInvalid {
            get {
                return ResourceManager.GetString("SearchLengthInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TERMS_NOT_ACCEPTED.
        /// </summary>
        public static string TermsNotAccepted {
            get {
                return ResourceManager.GetString("TermsNotAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TO_BEFORE_FROM.
        /// </summary>
        public static string ToBeforeFrom {
            get {
                return ResourceManager.GetString("ToBeforeFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOKEN_REQUIRED.
        /// </summary>
        public static string TokenRequired {
            get {
                return ResourceManager.GetString("TokenRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNITS_GREATER_THAN_ZERO.
        /// </summary>
        public static string UnitsGreaterThanZero {
            get {
                return ResourceManager.GetString("UnitsGreaterThanZero", resourceCulture);
            }
        }
    }
}
