name: Build

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  DOTNET_VERSION: 8.0.x

on:
  pull_request:
    branches: [ "main" ]

jobs:
  scan-lint:
    
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write   
      packages: read

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Lint
      run: dotnet format src/gluco-pilot.sln
    - name: Commit changes
      if: github.event_name == 'pull_request'
      uses: stefanzweifel/git-auto-commit-action@e256565ae56ff1c64fad2e063453107bf88f6aa1
      with:
        add_options: -u
        commit_message: Run code generators and linters
        branch: ${{ github.event.pull_request.head.ref }}

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore src/gluco-pilot.sln
    - name: Build
      run: dotnet build src/gluco-pilot.sln --no-restore
    - name: Test
      run: dotnet test src/gluco-pilot.sln --no-build --verbosity normal